from __future__ import annotations

import os
from typing import Sequence

import numpy as np
import plotly.graph_objects as go
from sklearn.metrics import (
    accuracy_score, classification_report, f1_score,
    precision_score, recall_score,
)
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

from .preprocessing import extend_xy_with_nearest_z, sample_xy
from .visualization import build_html_with_axis_controls


def train_svm_classifier(
    water_points: Sequence[np.ndarray],
    seabed_points: Sequence[np.ndarray],
    output_dir: str,
    extension_factor: float = 0.6,
    max_train_samples: int = 3_000,
    decision_grid_res: int = 25,
) -> dict:
    """Train a linear SVM on water/seabed points and visualise the decision boundary.

    The training set is augmented with synthetic boundary points generated by
    :func:`extend_xy_with_nearest_z` to improve extrapolation behaviour.

    Parameters
    ----------
    water_points, seabed_points:
        Sequences of (N, 3) [X, Y, Z] arrays (one per chunk).
    output_dir:
        Where to write the HTML visualisation.
    extension_factor:
        XY bounding-box expansion fraction for synthetic training data.
    max_train_samples:
        Cap on training-set size (random subsample if exceeded).
    decision_grid_res:
        Resolution of the 3-D decision-function grid (``res³`` evaluations).

    Returns
    -------
    dict with keys ``accuracy``, ``precision``, ``recall``, ``f1``,
    ``report`` and ``html_path``.
    """
    os.makedirs(output_dir, exist_ok=True)

    water_feat = np.concatenate(water_points, axis=0)
    seabed_feat = np.concatenate(seabed_points, axis=0)
    X = np.vstack([water_feat, seabed_feat])
    y = np.concatenate([
        np.ones(len(water_feat), dtype=int),
        np.zeros(len(seabed_feat), dtype=int),
    ])

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y,
    )

    # Augment with synthetic boundary points
    w_ext = extend_xy_with_nearest_z(water_feat, factor=extension_factor)
    s_ext = extend_xy_with_nearest_z(seabed_feat, factor=extension_factor)
    X_aug = np.vstack([X_train, w_ext, s_ext])
    y_aug = np.concatenate([
        y_train,
        np.ones(len(w_ext), dtype=int),
        np.zeros(len(s_ext), dtype=int),
    ])

    n = min(max_train_samples, len(X_aug))
    X_fit, y_fit = sample_xy(X_aug, y_aug, n=n)

    clf = SVC(kernel="linear")
    clf.fit(X_fit, y_fit)

    y_pred = clf.predict(X_test)
    metrics = {
        "accuracy": float(accuracy_score(y_test, y_pred)),
        "precision": float(precision_score(y_test, y_pred)),
        "recall": float(recall_score(y_test, y_pred)),
        "f1": float(f1_score(y_test, y_pred)),
        "report": classification_report(y_test, y_pred),
    }

    print(f"Accuracy : {metrics['accuracy']:.4f}")
    print(f"Precision: {metrics['precision']:.4f}")
    print(f"Recall   : {metrics['recall']:.4f}")
    print(f"F1-score : {metrics['f1']:.4f}")
    print("\nClassification report:\n", metrics["report"])

    # ------------------------------------------------------------------
    # 3-D decision boundary visualisation
    # ------------------------------------------------------------------
    margin = 0.05
    xl = np.linspace(X[:, 0].min() - margin, X[:, 0].max() + margin, decision_grid_res)
    yl = np.linspace(X[:, 1].min() - margin, X[:, 1].max() + margin, decision_grid_res)
    zl = np.linspace(X[:, 2].min() - margin, X[:, 2].max() + margin, decision_grid_res)
    xx, yy, zz = np.meshgrid(xl, yl, zl)
    decision = clf.decision_function(np.c_[xx.ravel(), yy.ravel(), zz.ravel()])
    dv = decision.reshape(decision_grid_res, decision_grid_res, decision_grid_res)

    rng = np.random.default_rng()

    def _sub(arr, n=1_000):
        return arr[rng.choice(len(arr), n, replace=False)] if len(arr) > n else arr

    W = _sub(water_feat)
    S = _sub(seabed_feat)

    fig = go.Figure(data=[
        go.Scatter3d(x=W[:, 0], y=W[:, 1], z=W[:, 2],
                     mode="markers", marker=dict(size=4, color="blue"), name="Water"),
        go.Scatter3d(x=S[:, 0], y=S[:, 1], z=S[:, 2],
                     mode="markers", marker=dict(size=4, color="orange"), name="Seabed"),
        go.Isosurface(
            x=xx.flatten(), y=yy.flatten(), z=zz.flatten(),
            value=dv.flatten(), isomin=0, isomax=0, surface_count=1,
            colorscale="Greens", showscale=False, opacity=0.5,
            name="Decision boundary",
        ),
    ])

    all_x = np.concatenate([W[:, 0], S[:, 0], xx.flatten()])
    all_y = np.concatenate([W[:, 1], S[:, 1], yy.flatten()])
    all_z = np.concatenate([W[:, 2], S[:, 2], zz.flatten()])
    mid_x, mid_y, mid_z = np.mean(all_x), np.mean(all_y), np.mean(all_z)
    half = max(np.ptp(all_x), np.ptp(all_y), np.ptp(all_z)) / 2 or 1.0
    xr = [mid_x - half, mid_x + half]
    yr = [mid_y - half, mid_y + half]
    zr_range = [mid_z - half, mid_z + half]

    fig.update_layout(
        scene=dict(
            xaxis=dict(title="X", range=xr),
            yaxis=dict(title="Y", range=yr),
            zaxis=dict(title="Z", range=zr_range),
            aspectmode="cube",
        ),
        title="SVM decision boundary (3-D isosurface)",
        legend=dict(x=0, y=1),
        width=900, height=800,
    )

    html = build_html_with_axis_controls(
        title="SVM_decision_boundary",
        inner_html=fig.to_html(include_plotlyjs="cdn", full_html=False),
        xrange_init=xr, yrange_init=yr, zrange_init=zr_range,
    )
    html_path = os.path.join(output_dir, "svm_decision_boundary.html")
    with open(html_path, "w", encoding="utf-8") as fh:
        fh.write(html)

    metrics["html_path"] = html_path
    return metrics


# Backward-compatible alias
prepare_and_vizualize_decission_borders = train_svm_classifier
